spring:
  application:
    name: discovery-service
server:
    port: 8761
 
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false

